name: Build master branch every night
on:
  workflow_dispatch:
  schedule:
    # nightly (min hour day month weekday)
    - cron: '11 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout actions
      uses: actions/checkout@v1
    - name: Check, build and push
      uses: ./.github/actions/check-deploy-push
      with:
        check-repository: pilight/pilight
        check-branch: master
        check-days: 2
        build-branch: master
        build-tags: akloeckner/pilight:latest
        push-username: ${{ secrets.DOCKERHUB_USERNAME }}
        push-password: ${{ secrets.DOCKERHUB_TOKEN }}
