name: Build staging branch every night
on:
  workflow_dispatch:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron: '1 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check for recent changes
      id: check_for_changes
      run: |
        commitdate=$(curl -sL "https://api.github.com/repos/pilight/pilight/commits/master" | jq -r ".commit.author.date")
        commitdays=$(( ( $(date --utc +%s) - $(date --utc -d $commitdate +%s) ) / 86400 ))
        echo "Last commit was $commitdays days ago."
        if [ $commitdays -lt 20000 ]; then
          echo "::set-output name=changes_exist::true"
          echo "Schedule following steps to RUN."
        else
          echo "::set-output name=changes_exist::false"
          echo "Schedule following steps to NOT RUN."
        fi

    - name: Checkout
      if: ${{ steps.check_for_changes.outputs.changes_exist == 'true' }}
      uses: actions/checkout@v2
      with:
        ref: master
      
    - name: Set up Docker Buildx
      if: ${{ steps.check_for_changes.outputs.changes_exist == 'true' }}
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      if: ${{ steps.check_for_changes.outputs.changes_exist == 'true' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the image
      if: ${{ steps.check_for_changes.outputs.changes_exist == 'true' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: akloeckner/pilight:latest

    - name: Image digest
      if: ${{ steps.check_for_changes.outputs.changes_exist == 'true' }}
      run: echo Image digest is ${{ steps.docker_build.outputs.digest }}
