name: Update docker hub description
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      docker_repo: akloeckner/pilight
      branch: master
    steps:

    - name: Check out
      uses: actions/checkout@v2
      with:
        ref: ${{ env.branch }}
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ env.docker_repo }}
        short-description: ${{ github.event.repository.description }}
